desc "Create on developer Portal and App Store Connect"
lane :create_app do
  create_app_online #produce
end

default_platform(:ios)

platform :ios do
  desc "Sync Signing"
  lane :signing do
 
  end

  desc "Build binary"
  lane :build do
	signing
  end

  desc "Release"
  lane :release do
	build
  end
end
